const mongoose = require("mongoose");

const Property = new mongoose.Schema({
  propertyId: { type: mongoose.Schema.Types.ObjectId },
  propertyImage: { type: [String], default: [] },
  propertyName: { type: String, default: "" },
  propertyLike: { type: Number, default: 0 },
  propertyDislike: { type: Number, default: 0 },
  propertyBedType: { type: String },
  propertyLandSize: { type: String,  },
  propertyDistance: { type: String, default: 0 },
  propertyStatus: { type: String },
  propertyCity: { type: String },
  propertyDeveloper: { type: String },
  propertyPinCode: { type: String },
  propertyLocality: { type: String },
  propertyAddress: { type: String },
  propertyType: { type: String },
  propertyTowerPhaseBuilding: { type: String },
  propertyFloorNumber: { type: String },
  propertyUnitNumber: { type: String },
  propertyNickName: { type: String },
  propertyBuitSizeCarpetSize: { type: String },
  propertyNumberOfBedrooms: { type: String },
  propertyNumberOfBathrooms: { type: String },
  propertyNumberOfCarParks: { type: String },
  propertyTypeOfFurnishing: { type: String },
  propertyIsAvailableRentSale: { type: String },
  propertyExpectedSalePrice: { type: String },
  propertyExpectedRent: { type: String },
  propertyRentalDeposit: { type: String },
  propertyMaintenanceIncExcl: { type: String },
  propertyAvailableFrom: { type: String },
  propertyCurrentStatus: { type: String },
  propertyViewingFrom: { type: String },
  propertyViewingNotice: { type: String },
  propertyViewingSlot: { type: String },
  propertyHelpersRoom: { type: String },
  isBalcony: { type: String },
  additionalAreas: { type: String },
  appliances: { type: String },
  isGarden: { type: String },
  isPetsAllowed: { type: String },
  isRenovated: { type: String },
  isMainDoorFacin: { type: String },
  ageOfProperty: { type: String },
  geoLocation: { type: String },
  propertyDescription: { type: String },
  createdAt: { type: Date, default: Date.now },
});

module.exports = mongoose.model("Property", Property);
